name: Faction
main: eu.fireblade.faction.Main
author: _goldocelot_
version: 0.0.2
commands:
 claim:
  description: Cette commande permet de claim un chunk.
 f:
  description: Permet de gerer les factions.