name: Faction
main: eu.fireblade.faction.Main
author: _goldocelot_
version: 0.0.3
commands:
 claim:
  description: Cette commande permet de claim un chunk.
 unclaim:
  description: Cette commande permet de retirer un claim.
 f:
  description: Permet de gerer les factions.